### ISSUE TITLE
Performance comparison of Agents.jl with other frameworks in a paper seems wrong

### ISSUE THREAD

**Issue by Tortar** [JuliaDynamics/ABM_Framework_Comparisons#10]
I was reading this paper: [Experimenting with Agent-Based Model Simulation Tools](https://doi.org/10.3390/app13010013) published in Applied Sciences journal which compares ABM frameworks in terms of usability and performance, their results about Agents.jl seem wrong, sometimes Mesa beats Agents.jl ! Something I think it's not possible :P. Don't know if you want to contact the authors to modify it so that they use the right metodology to benchmark agents.jl models, the comparison code is also on github at https://github.com/isislab-unisa/ABM_Comparison . Hope it's relevant to you!

**Comment by Datseris** [comment]
At the moment I am super busy to do anything about this... But since you have already read the paper, perhaps you could open an issue / raise an issue to the authors?

**Comment by Tortar** [comment]
yes, no problems, I filled an issure here: https://github.com/isislab-unisa/ABM_Comparison/issues/1
