### ISSUE TITLE
State latest comparison table somewhere that is citable

### ISSUE THREAD

**Issue by Datseris** [JuliaDynamics/ABM_Framework_Comparisons#30]
The last thing remaining is to somehow automate obtaining the table in a format that can be cited (by a simple link). The best way to do this is to store the results in a txt file after CI is done. But that is probably complicated. Although, documenter can do this by adding keys: https://documenter.juliadocs.org/stable/man/hosting/#GitHub-Actions

Enabling Zenodo would then also attach a DOI to the table and we can tag versions of this repo and each version gets its own DOI.

For now, we should nevertheless state the latest table in the readme. @Tortar

**Comment by Tortar** [comment]
Put a link to the CI log in the README, I agree with you about the rest
