### ISSUE TITLE
Use text instead of images for comparison table

### ISSUE THREAD

**Issue by Datseris** [JuliaDynamics/ABM_Framework_Comparisons#37]
Markdown supports table formats: https://www.markdownguide.org/extended-syntax/#tables

Tables are copy-pastable and can be converted to othe formats such as a `DataFrame`. Pictures are clunky to work with.

**Comment by Tortar** [comment]
I think we can use an html table for better formatting: https://stackoverflow.com/questions/46621765/can-i-merge-table-rows-in-markdown

**Comment by Datseris** [comment]
Why? Just use one row for each model, different rows for big and small. Markdown is the purest form and can later be processed easily to match other forms.

**Comment by Tortar** [comment]
Just a matter of taste, I liked more another format for the table, but there is not much of a difference anyway, so let's keep the current version and close the issue
