### ISSUE TITLE
Mismatch in Schelling implementation

### ISSUE THREAD

**Issue by Corvince** [JuliaDynamics/ABM_Framework_Comparisons#57]
I was looking into Mesas comparatively poor performance for the Schelling segregation model and realized that the models are not equivalent (disclaimer: I am one of the maintainers of mesa).

In Agents.jl you have the following line

`agent.mood == true && return# do nothing if already happy`

This shortcut does not exist for mesa so I was looking into this. Netlogo also just updates unhappy agents, whereas Mason also checks all agents (not sure).

Skimming through the original paper and some related articles left me clueless - there doesn't seem to be a "right" answer, but the results definitely differ. 

Take these three genderless Agents:
😑 😑 😑 

If we evaluate their happiness and assume they are happy with two neighbors we get the following result
😢 😆 😢 

The unhappy agents will move somewhere else and the next round looks like this (I meant to use the dotted line face emoji, but not available on github)
🌐 😆 🌐 

Should the Agent remain happy? Or should he move and pursuit happiness somewhere else? That's the difference of the early exit condition. 

To have a fair comparison all models should behave equally. 

For example enabling early exit for Mesa gives me a 3-5 times speed increase, so quite substantial! 

Personally I think early exit should be disabled for all agents (also to benchmark more than just "do nothing"), but again, there doesn't seem to be a correct answer.

**Comment by Datseris** [comment]
you are 100% right, I completely agree, all implementations should do the same. I thought all implementations skipped the happy agents but you're right, they don't. I don't see any skip in the Mesa implementation. Sure, I agree with your suggestion of simply eliminating the clause of "do nothing if agent unhappy" for Agents.jl and just always count nearby neighbors. Don't know what MASON does, I didn't write the implementation.

@Tortar any chance you can address this via a PR?

**Comment by Tortar** [comment]
Addressing it right now, I would als go with simply removing the clause

**Comment by Tortar** [comment]
Solved :+1:
