### ISSUE TITLE
suboptimal allocation of trees on fire in Agents.jl ForestFire implementation

### ISSUE THREAD

**Issue by Datseris** [JuliaDynamics/ABM_Framework_Comparisons#61]
This line does not appear optimal to me:

https://github.com/JuliaDynamics/ABM_Framework_Comparisons/blob/main/ForestFire/Agents/ForestFire.jl#L17

`findall(isequal(2), forest.trees)` allocates a vector with the burning trees. To do that, it _anyways_ iterates over all trees.

Wouldn't it faster to explicitly iterate ourselves and skip non burning trees? I.e., do

```julia
@inbounds for I in eachindex(forest.trees)
forest.trees[I] != 2 && continue
# remaining code is identical
```

**Comment by Tortar** [comment]
No it doesn't since probably findall is more optimized than a simple loop (I see a 2x difference).

However changing `trees = zeros(Int, griddims),)` in `trees = zeros(Int8, griddims),)` helps a bit in terms of performance

**Comment by Tortar** [comment]
Actually somewhat better than expected, forestfire-large in respect to Mesa passed from 494x to 645x
